--------------------------------------------------------
--  File created - Sunday-September-20-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUSTOMERS" SHARING=METADATA 
   (	"CUSTOMER_ID" NUMBER, 
	"CUSTOMER_NAME" VARCHAR2(100), 
	"EMAIL" VARCHAR2(100), 
	"CITY" VARCHAR2(50), 
	 PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ORDERS" 
   (	"ORDER_ID" NUMBER, 
	"CUSTOMER_ID" NUMBER, 
	"ORDER_DATE" DATE, 
	 PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "SYSTEM"."CUSTOMERS" ("CUSTOMER_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table ORDER_ITEMS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ORDER_ITEMS" 
   (	"ORDER_ITEM_ID" NUMBER, 
	"ORDER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	 PRIMARY KEY ("ORDER_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("ORDER_ID")
	  REFERENCES "SYSTEM"."ORDERS" ("ORDER_ID") ENABLE, 
	 FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "SYSTEM"."PRODUCTS" ("PRODUCT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PRODUCTS" SHARING=METADATA 
   (	"PRODUCT_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(100), 
	"CATEGORY" VARCHAR2(50), 
	"PRICE" NUMBER(10,2), 
	 PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
REM INSERTING into SYSTEM.CUSTOMERS
SET DEFINE OFF;
Insert into SYSTEM.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,EMAIL,CITY) values (1,'John Smith','john@gmail.com','Kigali');
Insert into SYSTEM.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,EMAIL,CITY) values (2,'Alice Uwase','alice@gmail.com','Huye');
Insert into SYSTEM.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,EMAIL,CITY) values (3,'David Mugisha','david@gmail.com','Musanze');
Insert into SYSTEM.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,EMAIL,CITY) values (4,'Sarah Mukamana','sarah@gmail.com','Rubavu');
Insert into SYSTEM.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,EMAIL,CITY) values (5,'Peter Niyonzima','peter@gmail.com','Kigali');
Insert into SYSTEM.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,EMAIL,CITY) values (6,'Grace Ingabire','grace@gmail.com','Muhanga');
Insert into SYSTEM.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,EMAIL,CITY) values (7,'Eric Habimana','eric@gmail.com','Kigali');
Insert into SYSTEM.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,EMAIL,CITY) values (8,'Diane Uwamahoro','diane@gmail.com','Huye');
REM INSERTING into SYSTEM.ORDERS
SET DEFINE OFF;
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (1,1,to_date('01-AUG-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (2,2,to_date('03-AUG-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (3,3,to_date('05-AUG-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (4,1,to_date('07-AUG-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (5,4,to_date('10-AUG-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (6,5,to_date('12-AUG-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (7,2,to_date('15-AUG-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (8,3,to_date('18-AUG-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (9,6,to_date('20-AUG-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (10,1,to_date('22-AUG-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (11,4,to_date('24-AUG-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (13,7,to_date('28-AUG-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (14,2,to_date('30-AUG-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (15,1,to_date('02-SEP-26','DD-MON-RR'));
Insert into SYSTEM.ORDERS (ORDER_ID,CUSTOMER_ID,ORDER_DATE) values (12,5,to_date('26-AUG-26','DD-MON-RR'));
REM INSERTING into SYSTEM.ORDER_ITEMS
SET DEFINE OFF;
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (1,1,1,2);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (2,1,4,3);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (3,2,2,2);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (4,2,7,3);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (5,3,3,2);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (6,3,9,2);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (7,4,8,1);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (8,4,10,4);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (9,5,1,1);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (10,5,6,2);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (11,6,5,4);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (12,6,11,2);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (13,7,3,3);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (14,7,7,2);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (15,8,2,5);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (16,8,12,2);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (17,9,4,4);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (18,9,9,3);
Insert into SYSTEM.ORDER_ITEMS (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY) values (19,10,1,1);
REM INSERTING into SYSTEM.PRODUCTS
SET DEFINE OFF;
Insert into SYSTEM.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE) values (1,'Rice 5kg','Groceries',8500);
Insert into SYSTEM.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE) values (2,'Sugar 2kg','Groceries',3000);
Insert into SYSTEM.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE) values (3,'Cooking Oil 1L','Groceries',4500);
Insert into SYSTEM.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE) values (4,'Milk 1L','Dairy',1500);
Insert into SYSTEM.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE) values (5,'Yogurt','Dairy',1200);
Insert into SYSTEM.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE) values (6,'Cheese 500g','Dairy',6500);
Insert into SYSTEM.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE) values (7,'Bread','Bakery',1200);
Insert into SYSTEM.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE) values (8,'Chocolate Cake','Bakery',7500);
Insert into SYSTEM.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE) values (9,'Orange Juice','Beverages',2500);
Insert into SYSTEM.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE) values (10,'Mineral Water','Beverages',1000);
Insert into SYSTEM.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE) values (11,'Coffee 250g','Beverages',4000);
Insert into SYSTEM.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE) values (12,'Tea 100 Bags','Beverages',3500);
